// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PluginCommonBase","status":true,"description":"パラメータ解析を提供する共通基盤です","parameters":{}},
{"name":"ParallaxLayerMap","status":true,"description":"多層レイヤー一枚絵マッププラグイン","parameters":{}},
{"name":"TemplateEvent","status":true,"description":"テンプレートイベントプラグイン","parameters":{"TemplateMapId":"1","KeepEventId":"false","OverrideTarget":"","AutoOverride":"false","IntegrateNote":"0"}},
{"name":"EventReSpawn","status":true,"description":"イベント動的生成プラグイン","parameters":{"keepSelfSwitch":"false","tryRandomCount":"1000","CertainSpawnSwitch":"0"}}
];
